version: '3.3'

volumes:
  pg_data:
  static_django:
  media:


services:
  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  frontend:
    build:
      context: dentretyakoff/foodgram_frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  backend:
    build: dentretyakoff/foodgram_backend
    env_file: ../.env
    volumes:
      - static_django:/backend_static
      - media:/app/media_files
    depends_on:
      - db
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        cp -r /app/collected_static/. /backend_static/ &&
        gunicorn --bind 0.0.0.0:8000 foodgram_backend.wsgi"
  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_django:/backend_static/
      - media:/media_files
    depends_on:
      - backend
